apiVersion: v1
kind: Pod
metadata:
  name: s3-test-pod
  namespace: default
spec:
  containers:
  - name: app
    image: alpine
    command: ["/bin/sh", "-c"]
    args:
    - |
      while true; do
        echo "$(date): Hello from K8s pod to Yandex Object Storage!" >> /mnt/s3/timestamp.txt;
        sleep 5;
      done
    volumeMounts:
    - name: s3-volume
      mountPath: /mnt/s3
  volumes:
  - name: s3-volume
    persistentVolumeClaim:
      claimName: s3-pvc