apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
  namespace: homework
  labels:
    app: web-server
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  
      maxSurge: 1        
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      nodeSelector:
        homework: "true"
      initContainers:
      - name: init-generator
        image: busybox
        command: ['sh', '-c', 'echo "Hello from init container" > /homework/index.html']
        volumeMounts:
        - name: shared-data
          mountPath: "/homework"
      containers:
      - name: web-server
        image: python:3.9-slim

        command: ["python3", "-m", "http.server", "8000", "--directory", "/homework"]
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: shared-data
          mountPath: /homework
        readinessProbe:
          httpGet:
            path: /
            port: 8000
       
          failureThreshold: 3
          periodSeconds: 10
        lifecycle:
          preStop:
            exec:

              command: ["sh", "-c", "sleep 5"]
      volumes:
      - name: shared-data
        emptyDir: {}