replicaCount: 1

image:
  repository: nexus.k8s.local:8082/quote-backend
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

env:
  dbUrl: "jdbc:postgresql://postgres-postgresql.default.svc.cluster.local:5432/quotesdb"
  dbUser: "postgres"
  dbPassword: "secretpassword"