[bastion]
bastion_host ansible_host=198.51.100.25  # <-- Твой ПУБЛИЧНЫЙ IP Бастиона

[k8s_master]
master_host ansible_host=10.128.0.10     # <-- Внутренний IP Master-ноды

[k8s_workers]
worker_host ansible_host=10.128.0.11     # <-- Внутренний IP Worker-ноды

[external_docker]
gitlab_host ansible_host=10.128.0.20     # <-- Внутренний IP GitLab
nexus_host ansible_host=10.128.0.21      # <-- Внутренний IP Nexus

[external_postgres]
postgres_host ansible_host=10.128.0.30   # <-- Внутренний IP PostgreSQL

# -----------------------------------------------------------------------------
# Глобальные настройки подключения для всех хостов
# -----------------------------------------------------------------------------
[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519  # Путь к твоему приватным ключу
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'