[all]
master-1 ansible_host=192.168.10.11 ip=192.168.10.11 ansible_user=ubuntu
master-2 ansible_host=192.168.10.12 ip=192.168.10.12 ansible_user=ubuntu
master-3 ansible_host=192.168.10.13 ip=192.168.10.13 ansible_user=ubuntu
worker-1 ansible_host=192.168.10.14 ip=192.168.10.14 ansible_user=ubuntu
worker-2 ansible_host=192.168.10.15 ip=192.168.10.15 ansible_user=ubuntu

[kube_control_plane]
master-1
master-2
master-3

[etcd]
master-1
master-2
master-3

[kube_node]
worker-1
worker-2

[calico_rr]

[k8s_cluster:children]
kube_control_plane
kube_node
calico_rr