apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-exporter # Лейбл для поиска
  template:
    metadata:
      labels:
        app: nginx-exporter
    spec:
      containers:
      - name: nginx
        image: petrovichpower/nginx-metrics:v1 # Твой образ
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:latest
        args: ["-nginx.scrape-uri=http://localhost/basic_status"]

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-exporter
spec:
  ports:
  - port: 9113
    name: metrics
  selector:
    app: nginx-exporter