apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitor
  labels:
    release: prometheus # ВАЖНО: должно совпадать с названием релиза Helm
spec:
  selector:
    matchLabels:
      app: nginx-exporter
  endpoints:
  - port: metrics