apiVersion: v1
kind: Service
metadata:
  name: metrics-service
  namespace: homework
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30082
  selector:
    app: web-server