apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: otus-cred-es
  namespace: vault
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: otus-cred  # Имя итогового K8s Secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: data/cred # Путь внутри KV v2 (снаружи добавляется data/)
      property: username
  - secretKey: password
    remoteRef:
      key: data/cred
      property: password