apiVersion: v1
kind: Pod
metadata:
  name: homework-pod
  namespace: homework
spec:

  volumes:
  - name: shared-data
    emptyDir: {}


  initContainers:
  - name: init-generator
    image: busybox
    command: ['sh', '-c', 'echo "Hello from init container" > /init/index.html']
    volumeMounts:
    - name: shared-data
      mountPath: /init


  containers:
  - name: web-server
    image: python:3.9-slim
    command: ["python3", "-m", "http.server", "8000", "--directory", "/homework"]
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: shared-data
      mountPath: /homework
    
    lifecycle:
      preStop:
        exec:
          command: ["rm", "/homework/index.html"]
